### ISSUE TITLE
How do I "Un-Gruvbox" pictures? Most of them look like paintings. 

### ISSUE THREAD

**Issue by YuvanMichaelVivenzi** [ficonni/gruvbox-cars#1]
I know that's just the gruvbox color scheme but all images in this repo look like literal paintings that imitate real life things, It's good for some and not good for others, there are times when I wish there was a "un-gruvbox" thing or a program that could undo this, If not, do you still have a backup of the "original" pictures? I would like to check the real pictures. 

Thanking you in advance. 

Yuvan Michael Vivenzi

**Comment by ficonni** [comment]
HI, thanks for the interest.

I've just took a look at my external hard drive where I put some backups for the wallpapers, as I frankly created this repo so that I didn't have to backup any of these images anymore (back in the day I often changed Linux distros a lot and always used the Gurvbox theme. I always wiped my hard drive simply because there was always a lot of bloat on my system).

It appears only some of my F1 wallpapers survived, which I used gruvbox-factory with. I'll upload them in a new repo. 

I doubt it's possible to "un-gruvbox" them. as gruvbox-factory basically converts the images into only 16 colors.

I agree the results are mixed. If you want I can give you links to some of the sites I used to get the images, and I will upload a "ungruvboxed-cars" repo now. I think there will be around 30-50 images in total. 

Honestly I'm dissapointed myself to see I didn't backup all of the images such as the IMSA series, NASCAR and whatever. I was sure I did.

**Comment by ficonni** [comment]
I also just checked my cloud storage. It seems I will be able to get more of these images that are not present on my hard drive, but it's not the full collection by a long shot sadly.

**Comment by ficonni** [comment]
Check out
[https://github.com/ficonni/ungruvboxed-cars](url) for the surviving pictures.

Also, check out sites like :

[https://www.reddit.com/r/F1Porn/top/?t=all](url)

[https://www.f1-fansite.com/f1-wallpapers/](url)

[https://www.wallpaperflare.com/search?wallpaper=F1](url)

and the link for my sources. Usually I just googled "WEC Wallpaper " or the like to find the picutres.

Sadly, I don't think there's more than that I can do to help, but I hope this was of some value.

**Comment by ficonni** [comment]
P.S. maybe reverse image search would be of some help here ?

**Comment by YuvanMichaelVivenzi** [comment]
Thanks for your help! Will check the links and reverse image search as well. Probably safe to close this now. :D

**Comment by YuvanMichaelVivenzi** [comment]
Apparently there is no way to "un-gruvbox" as the "color mapping is lost" according to the author of the gruvbox-factory repo. So, there you go. But, the resources you provided were pretty helpful. Thanks for your help. :D

**Comment by ficonni** [comment]
No problem mate :)
Shame there's nothing more we can do.

I think there might also be [official wallpapers for WEC on the site ](https://www.fiawec.com/en/photos-videos/13). Also, there's some good images I found (mostly of the LMGT3 class if I remember) on [their Twitter](https://x.com/FIAWEC).

[Here's something that might interest you as well](https://imgur.com/a/racing-wallpapers-hd-eOWP1RR). Just found this out while searching the WEC wallpapers.
